# Generated by Django 4.2 on 2023-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_pic_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/user.jpg', max_length=300, upload_to='images'),
        ),
    ]
