# Generated by Django 4.2 on 2023-05-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('image1', models.ImageField(default='images/Harrier.jpg', upload_to='images')),
                ('image2', models.ImageField(default='images/Harrier.jpg', upload_to='images')),
                ('image3', models.ImageField(default='images/Harrier.jpg', upload_to='images')),
                ('image4', models.FileField(null=True, upload_to='documents')),
                ('fuel', models.CharField(default='Petrol', max_length=20)),
                ('rent_price', models.IntegerField(default=100)),
                ('description', models.TextField(default='', max_length=1024)),
                ('ac', models.CharField(default='Yes', max_length=20)),
                ('location', models.CharField(max_length=100, null=True)),
                ('is_accepted', models.CharField(choices=[('verifying', 'verifying'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='verifying', max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.category')),
                ('renter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='renters.renters')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.category'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent', models.IntegerField(null=True)),
                ('total_rent', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Razor_Pay', 'Razor_Pay'), ('Wallet', 'Wallet')], default='Razor_Pay', max_length=100)),
                ('transaction_id', models.CharField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('cancelled', 'cancelled')], default='paid')),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
