# Generated by Django 4.2 on 2023-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_booking_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='withdrawal_status',
            field=models.BooleanField(default=False),
        ),
    ]
